### ISSUE TITLE
Note in readme about using alternate Gutenberg mirrors

### ISSUE THREAD

**Issue by AbrahamSanders** [ricsinaruto/gutenberg-dialog#4]
Hi @ricsinaruto! I absolutely love this project and the idea of extracting dialog datasets from books.

I wanted to share a small issue I ran into when running the pipeline. By default, the `gutenberg` package attempts to use the mirror http://aleph.gutenberg.org for downloading the books, when `gutenberg.acquire.load_etext(...)` is called from `download.py`. For some reason this mirror was down, and I got the message "Could not download book" for every book in the list.

A little digging revealed that the `gutenberg` library allows an alternate mirror to be specified as an environment variable - you can specify any mirror URL from https://www.gutenberg.org/MIRRORS.ALL and set it to the env. variable `GUTENBERG_MIRROR` before running the code. For example,

```
export GUTENBERG_MIRROR="https://gutenberg.pglaf.org"
python code/main.py ...
```

I thought it might be helpful to mention this somewhere in the readme to save others from scratching their head on this! What do you think? I can submit a PR for it if that is ok.

Best regards and thanks again for this amazing work!

**Comment by ricsinaruto** [comment]
Hi Abraham!

Thank you very much for spotting this. I am more than happy to accept the PR if you create it :)

**Comment by AbrahamSanders** [comment]
Awesome! Please see #5

**Comment by ricsinaruto** [comment]
thank you, I merged it!
